# SPDX-FileCopyrightText: 2026 NVEIL SAS
# SPDX-License-Identifier: AGPL-3.0-or-later
site_name: Frontend
nav:
  - Overview: index.md
  - Architecture:
      - Index: architecture/index.md
      - Api: architecture/api.md
      - I18N: architecture/i18n.md
      - Routing: architecture/routing.md
      - State: architecture/state.md
  - Components:
      - Index: components/index.md
  - Developer:
      - Index: developer/index.md
      - Adding Pages: developer/adding-pages.md
      - Separation: developer/separation.md
      - Styling: developer/styling.md
      - Testing: developer/testing.md
  - Pages:
      - Index: pages/index.md
      - Auth: pages/auth.md
      - Dashboard: pages/dashboard.md
      - Data: pages/data.md
      - Home: pages/home.md
      - Viz: pages/viz.md
