// SPDX-FileCopyrightText: 2026 NVEIL SAS
// SPDX-FileContributor: Pierre Jacquet
// SPDX-License-Identifier: AGPL-3.0-or-later

// End-to-end: ask the AI to build a visualization from the CSV uploaded
// in test 04. Validates the full upload → link → chat → AI → viz pipeline:
//
//   1. POST /server/rooms/{room_id}/link-files [file_id]   ← file → room
//   2. POST /ai/sendUserMessage with a viz prompt
//   3. Server pushes `chat_response` WS frame once AI replies
//   4. AI generates a Choregraph spec → viz pod renders → server pushes
//      `viz_loaded` WS frame
//
// Without step 1 the AI sees the prompt but can't access the file (which
// is what was happening before — "No viz XML generated by LLM" because
// the file isn't in the room's data refs).
//
// Both events must arrive. AI latency is variable (typical 5–30 s
// locally); we give viz_loaded 120 s to cover transient AI retries.

import { test, expect } from './_fixture.js';
import { assertAuthenticated } from './_fixture.js';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { waitForWsFrame } from '../utils/wait-helpers.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOM_STATE = path.join(__dirname, '..', '.auth', 'room-under-test.json');

test('07 — link uploaded CSV to room, ask AI to plot it, wait for viz_loaded', async ({ sharedPage: page }, testInfo) => {
  await assertAuthenticated(page);
  expect(fs.existsSync(ROOM_STATE), 'no room available — 05-room-create must run first').toBe(true);
  const { roomToken, roomId } = JSON.parse(fs.readFileSync(ROOM_STATE, 'utf8'));
  expect(roomId, '05-room-create must have saved room_id').toBeTruthy();

  // Skip reload if we're already on the room page (06-room-open got us here).
  const expectedPath = `/room/${roomToken}`;
  if (!page.url().endsWith(expectedPath)) {
    await page.goto(expectedPath, { waitUntil: 'load' });
  }

  // ── 1. Link the uploaded CSV (test 04) to this room ──────────────
  const listResp = await page.request.get('/server/data/list');
  expect(listResp.ok(), 'data/list should be reachable').toBeTruthy();
  const listBody = await listResp.json();
  const csvFile = (listBody.files || []).find(f =>
    (f.original_name || f.display_name || '').includes('sample-small')
  );
  expect(csvFile?.id, 'sample-small.csv should exist (uploaded in 04)').toBeTruthy();

  const linkResp = await page.request.post(`/server/rooms/${roomId}/link-files`, {
    data: { file_ids: [csvFile.id] },
  });
  expect(linkResp.status(), `link-files should be 2xx, got body: ${await linkResp.text().catch(() => '?')}`)
    .toBeGreaterThanOrEqual(200);
  expect(linkResp.status()).toBeLessThan(300);

  // ── 2. Send the chat prompt ─────────────────────────────────────
  // sample-small.csv columns: date, product, revenue, cost, units
  const prompt = 'Using sample-small.csv, plot total revenue per product as a bar chart.';

  // Listen for both WS frames BEFORE sending.
  const chatResponsePromise = waitForWsFrame(
    page,
    (f) => f?.event === 'chat_response' || f?.type === 'chat_response',
    90_000
  ).catch(err => ({ __error: err.message }));

  const vizLoadedPromise = waitForWsFrame(
    page,
    (f) => f?.event === 'viz_loaded' || f?.type === 'viz_loaded',
    120_000   // AI gen + spec applied + viz pod render
  ).catch(err => ({ __error: err.message }));

  const t0 = Date.now();
  const sendResp = await page.request.post('/ai/sendUserMessage', {
    data: { messages: [{ text: prompt }] },
  });
  expect(sendResp.status(), `sendUserMessage should be 2xx, got body: ${await sendResp.text().catch(() => '?')}`)
    .toBeGreaterThanOrEqual(200);
  expect(sendResp.status()).toBeLessThan(300);

  // ── 3. AI must reply ─────────────────────────────────────────────
  const chatResp = await chatResponsePromise;
  const tChat = Date.now() - t0;
  expect(chatResp?.__error, `chat_response should arrive within 90s, got: ${chatResp?.__error}`).toBeFalsy();
  console.log(`Chat sent → chat_response: ${tChat}ms`);

  // ── 4. Viz must actually be built ────────────────────────────────
  const vizFrame = await vizLoadedPromise;
  const tViz = Date.now() - t0;
  expect(vizFrame?.__error, `viz_loaded should arrive within 120s, got: ${vizFrame?.__error}`).toBeFalsy();
  console.log(`Chat sent → viz_loaded: ${tViz}ms`);

  await testInfo.attach('chat-outcome.json', {
    body: JSON.stringify({
      prompt,
      file_id: csvFile.id,
      tChat,
      tViz,
      chat_response: chatResp,
      viz_loaded: vizFrame,
    }, null, 2),
    contentType: 'application/json',
  });
});
