# SPDX-FileCopyrightText: 2026 NVEIL SAS
# SPDX-FileContributor: Guillaume Franque
# SPDX-FileContributor: Clément Baraille
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Shared utilities for reading/writing .env configuration."""

import base64
import os
import secrets
from pathlib import Path

WORKSPACE = Path("/workspace").resolve()

PLACEHOLDER_PASSWORDS = {"nveil-community", "ai-community", "auto", "CHANGE_ME"}

LANGFUSE_KEYS = ("LANGFUSE_TRACING", "LANGFUSE_PUBLIC_KEY", "LANGFUSE_SECRET_KEY")

# Compose profiles. The app stack runs under "core" (the directory default via
# COMPOSE_PROFILES, so a bare `docker compose up` brings it up). The optional
# Langfuse stack runs under "tracing", started as a SEPARATE project with an
# explicit `--profile tracing` (which overrides COMPOSE_PROFILES) so it never
# pulls in — or gets pulled into — the core stack.
CORE_PROFILE = "core"
TRACING_PROFILE = "tracing"

ENV_KEYS = [
    "POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_DB",
    "AI_DB_PASSWORD", "DATABASE_SCHEMA",
    "SECRET_KEY", "ALGORITHM", "APP_ENCRYPTION_KEY",
    "GOOGLE_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY",
    "MISTRAL_API_KEY",
    "OLLAMA_BASE_URL", "OLLAMA_MODEL",
    "LLAMACPP_BASE_URL", "LLAMACPP_MODEL",
    "OPENAI_COMPAT_BASE_URL", "OPENAI_COMPAT_API_KEY", "OPENAI_COMPAT_MODEL",
    "DIVE_DATA_PATH",
    *LANGFUSE_KEYS,
]

DEFAULTS = {
    "POSTGRES_USER": "nveil",
    "POSTGRES_DB": "nveil",
    "DATABASE_SCHEMA": "nveilseption",
    "ALGORITHM": "HS512",
    "DIVE_DATA_PATH": "nveil-dive-data",
}


def _is_truthy(v) -> bool:
    return str(v).strip().lower() in ("1", "true", "yes", "on")


def _read_dot_env(path):
    out = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def get_current_values():
    dot_env = _read_dot_env(WORKSPACE / ".env")
    values = {}
    for k in ENV_KEYS:
        values[k] = dot_env.get(k, DEFAULTS.get(k, ""))
    return values


def auto_generate(values):
    if values.get("POSTGRES_PASSWORD") in PLACEHOLDER_PASSWORDS or not values.get("POSTGRES_PASSWORD"):
        values["POSTGRES_PASSWORD"] = secrets.token_hex(24)
    if values.get("AI_DB_PASSWORD") in PLACEHOLDER_PASSWORDS or not values.get("AI_DB_PASSWORD"):
        values["AI_DB_PASSWORD"] = secrets.token_hex(16)
    if values.get("SECRET_KEY") in PLACEHOLDER_PASSWORDS or len(values.get("SECRET_KEY", "")) < 32:
        values["SECRET_KEY"] = secrets.token_hex(64)
    if values.get("APP_ENCRYPTION_KEY") in PLACEHOLDER_PASSWORDS or not values.get("APP_ENCRYPTION_KEY"):
        values["APP_ENCRYPTION_KEY"] = base64.urlsafe_b64encode(os.urandom(32)).decode()
    if values.get("LANGFUSE_PUBLIC_KEY") in PLACEHOLDER_PASSWORDS:
        values["LANGFUSE_PUBLIC_KEY"] = f"pk-lf-{secrets.token_hex(16)}"
    if values.get("LANGFUSE_SECRET_KEY") in PLACEHOLDER_PASSWORDS:
        values["LANGFUSE_SECRET_KEY"] = f"sk-lf-{secrets.token_hex(16)}"
    return values


def write_dot_env(values, path=None):
    if path is None:
        path = WORKSPACE / ".env"
    with open(path, "w") as f:
        f.write("# Generated by Nveil Setup\n")
        for k in ENV_KEYS:
            if k in values:
                f.write(f"{k}={values[k]}\n")


def write_langfuse_env(values, path=None):
    """Persist Langfuse opt-in keys to .env.

    docker-compose references the Langfuse vars via ${VAR:-default}
    substitution, shared by the `ai` service and `langfuse-web`, so they must
    live in .env rather than the compose YAML. Existing .env entries are
    preserved; only the Langfuse keys are updated.
    """
    if path is None:
        path = WORKSPACE / ".env"
    existing = _read_dot_env(path)
    for k in LANGFUSE_KEYS:
        if k in values:
            existing[k] = values[k]

    # Default the directory to the "core" profile so a bare `docker compose up`
    # brings up the app stack. Never include "tracing": Langfuse runs as a
    # separate project started with an explicit `--profile tracing` (which
    # overrides COMPOSE_PROFILES), so listing it here would wrongly start it
    # inside the main nveil-community project.
    profiles = [
        p for p in existing.get("COMPOSE_PROFILES", "").split(",")
        if p.strip() and p.strip() != TRACING_PROFILE
    ]
    if CORE_PROFILE not in profiles:
        profiles.insert(0, CORE_PROFILE)
    existing["COMPOSE_PROFILES"] = ",".join(profiles)

    with open(path, "w") as f:
        f.write("# Generated by Nveil Setup\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")
