# SPDX-FileCopyrightText: 2026 NVEIL SAS
# SPDX-License-Identifier: AGPL-3.0-or-later
site_name: NVEIL Platform
nav:
  - Overview: index.md
  - Self-hosting: self-hosting.md
  - From your code: from-code.md
